apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 namespace: roboshop
 labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mongodb
      tier: db 
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mongodb
        tier: db 
    spec:
      containers:
      - name: mongodb
        image: nikitha84/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10 
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    componet: mongodb
    tier: db 
  ports:
  - protocol: TCP
    ports: 27017
    targetPort: 27017  


