apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 namespace: roboshop
 labels:
    project: roboshop
    environment: dev
    componet: mongodb
    tier: db
spec:
  replicas: 1
  selectore:
    matchLabels:
      project: roboshop
      environment: dev
      componet: mongodb
      tier: db 
template:
  matadata:
    labels:
      project: roboshop
      environment: dev
      componet: mongodb
      tier: db 
  spec:
    containers:
    - name: mongodb
      image: nikitha84/mongodb:v1
      imagePullPolicy: Always
    readinessProbe:
      tcpSocket:
        port: 27017
      initialDelaySeconds: 10 
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 27017
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kins: Service
metadata:
  name: mongdb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    componet: mongodb
    tier: db 
  ports:
    - protocol: TCP
      ports: 27017
      targetPort: 27017  


