apiVersion: v1 
kind: ConfigMap
metadata:
 name: catalogue-configmap
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
 name: catalogue
 namespace: roboshop
 labels:
    project: roboshop
    environment: dev
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: catalogue
      tier: backend 
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: catalogue
        tier: backend 
    spec:
      containers:
      - name: catalogue
        image: nikitha84/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue-configmap

        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15 #this is catalogue work on http
    
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: catalogue
    tier: backend 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080  







#kubetl apply
#kubetl get pods
#kubetl exec -it debug -- bash'
#telnet catalogue 8080=connected
#curl http://catalogue:8080/health = mongo=true
#nslookup catalogue

